openapi: 3.0.3
info:
  title: Bill Parser API
  description: API that parses bill text to extract structured data like merchant, amount, date and category.
  version: 1.0.0

paths:
  /process_bill:
    post:
      summary: Process bill text
      description: Takes bill text and extracts structured information including merchant name, amount, date and category.
      operationId: processBill
      tags:
        - Bill Processing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BillRequest"
      responses:
        "200":
          description: Successfully processed bill text
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BillResponse"
        "400":
          description: Invalid request format
        "500":
          description: Internal server error

components:
  schemas:
    BillRequest:
      type: object
      required:
        - text
      properties:
        text:
          type: string
          description: The raw text content of the bill

    BillResponse:
      type: object
      properties:
        merchant_name:
          type: string
          description: Name of the merchant from the bill
        total_amount:
          type: string
          description: Extracted total amount from the bill
        date:
          type: string
          description: Extracted date from the bill
        category:
          type: string
          description: Predicted category of the bill